name: coverage-report
on:
  pull_request:
  push:

jobs:
  coveragereport:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: go test -coverprofile ./c.out  $(go list ./... | grep -v /mock/)

    - name: Update coverage report
      uses: ncruces/go-coverage-report@v0
      with:
        coverage-file: ./c.out
        report: true
        chart: true
        amend: true
      continue-on-error: true